version: '3.7'
services:
  db:
    build:
      context: ./db
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "28080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  appstore:
    build:
      context: ./appstore-service
    ports:
      - 8005:8005
    environment:
      - SQLALCHEMY_DATABASE_URL=postgres://pop:password1@db/pop

  calculation-cockpit:
    build:
      context: ./calculation-cockpit-service
    ports:
      - 8006:8005

  datashelf:
    build:
      context: ./datashelf-service
    ports:
      - 8007:8005


volumes:
  postgres_data:
    name: postgres_data
  pgadmin-data:
    name: pgadmin-data
