version: '3.7'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    environment:
      - APPSTORE_URL=appstore:8005
      - CALCULATION_COCKPIT_URL=calculation-cockpit:8005
      - DATASHELF_URL=datashelf:8005
